name: clean_bloc_template
description: A minimal Clean Architecture + BLoC template (skeleton).
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^7.7.0
  injectable: ^2.5.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  go_router: ^16.2.5
  flutter_dotenv: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.5.5
  json_serializable: ^6.9.0
  injectable_generator: ^2.5.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
